name: php7.4 - Update Release

env:
  docker_registry: pnksh
  docker_repo: 'php-alpine'
  docker_tag: 'php7.4'

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f php/${{ env.docker_tag }}/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }} .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}
  
  build-with-node:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f php/${{ env.docker_tag }}/WithNode/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}-node:${{ env.docker_tag }} .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-node
