name: python3.10 - Update Release

env:
  docker_registry: pnksh
  docker_repo: 'python'
  docker_tag: 'python3.10'

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  
jobs:
  build-alpine-newrelic-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f python/${{ env.docker_tag }}/newrelic-agent/DockerfileAlpine -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-alpine-newrelic-agent .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-alpine-newrelic-agent

  build-newrelic-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f python/${{ env.docker_tag }}/newrelic-agent/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-newrelic-agent .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-newrelic-agent
