name: php7.2 - Update Release

env:
  docker_registry: pnksh
  docker_repo: 'php'
  docker_tag: 'php7.2'

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  
jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f php/${{ env.docker_tag }}/alpine/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-alpine .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-alpine

  build-buster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f php/${{ env.docker_tag }}/debian-buster/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-buster .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}-buster
